/** Audio WebM/Opus procesado para la guía de Mi Vereda. */
export const GUIA_AUDIO_ASSETS = {
  paso_01_bienvenida_explicacion: "/audio/mi-vereda/01_bienvenida_explicacion.webm",
  paso_01_bienvenida_invitacion: "/audio/mi-vereda/01_bienvenida_invitacion.webm",
  paso_01_bienvenida_confirmacion: "/audio/mi-vereda/01_bienvenida_confirmacion.webm",
  paso_01_bienvenida_omitir: "/audio/mi-vereda/01_bienvenida_omitir.webm",
  paso_02_elegir_vereda_explicacion: "/audio/mi-vereda/02_elegir_vereda_explicacion.webm",
  paso_02_elegir_vereda_invitacion: "/audio/mi-vereda/02_elegir_vereda_invitacion.webm",
  paso_02_elegir_vereda_confirmacion: "/audio/mi-vereda/02_elegir_vereda_confirmacion.webm",
  paso_02_elegir_vereda_omitir: "/audio/mi-vereda/02_elegir_vereda_omitir.webm",
  paso_03_novedades_explicacion: "/audio/mi-vereda/03_novedades_explicacion.webm",
  paso_03_novedades_invitacion: "/audio/mi-vereda/03_novedades_invitacion.webm",
  paso_03_novedades_confirmacion: "/audio/mi-vereda/03_novedades_confirmacion.webm",
  paso_03_novedades_omitir: "/audio/mi-vereda/03_novedades_omitir.webm",
  paso_04_historial_explicacion: "/audio/mi-vereda/04_historial_explicacion.webm",
  paso_04_historial_invitacion: "/audio/mi-vereda/04_historial_invitacion.webm",
  paso_04_historial_confirmacion: "/audio/mi-vereda/04_historial_confirmacion.webm",
  paso_04_historial_omitir: "/audio/mi-vereda/04_historial_omitir.webm",
  paso_05_filtros_explicacion: "/audio/mi-vereda/05_filtros_explicacion.webm",
  paso_05_filtros_invitacion: "/audio/mi-vereda/05_filtros_invitacion.webm",
  paso_05_filtros_confirmacion: "/audio/mi-vereda/05_filtros_confirmacion.webm",
  paso_05_filtros_omitir: "/audio/mi-vereda/05_filtros_omitir.webm",
  paso_06_solucionados_explicacion: "/audio/mi-vereda/06_solucionados_explicacion.webm",
  paso_06_solucionados_invitacion: "/audio/mi-vereda/06_solucionados_invitacion.webm",
  paso_06_solucionados_confirmacion: "/audio/mi-vereda/06_solucionados_confirmacion.webm",
  paso_06_solucionados_omitir: "/audio/mi-vereda/06_solucionados_omitir.webm",
  paso_07_no_solucionados_explicacion: "/audio/mi-vereda/07_no_solucionados_explicacion.webm",
  paso_07_no_solucionados_invitacion: "/audio/mi-vereda/07_no_solucionados_invitacion.webm",
  paso_07_no_solucionados_confirmacion: "/audio/mi-vereda/07_no_solucionados_confirmacion.webm",
  paso_07_no_solucionados_omitir: "/audio/mi-vereda/07_no_solucionados_omitir.webm",
  paso_08_cierre_explicacion: "/audio/mi-vereda/08_cierre_explicacion.webm",
  paso_08_cierre_invitacion: "/audio/mi-vereda/08_cierre_invitacion.webm",
  paso_08_cierre_confirmacion: "/audio/mi-vereda/08_cierre_confirmacion.webm",
  paso_08_cierre_omitir: "/audio/mi-vereda/08_cierre_omitir.webm",
  transicion_01_preparacion: "/audio/mi-vereda/transicion_01_preparacion.webm",
  transicion_02_absorcion: "/audio/mi-vereda/transicion_02_absorcion.webm",
  transicion_03_transito: "/audio/mi-vereda/transicion_03_transito.webm",
  transicion_04_reaparicion: "/audio/mi-vereda/transicion_04_reaparicion.webm",
  transicion_05_senalamiento: "/audio/mi-vereda/transicion_05_senalamiento.webm",
  transicion_06_espera: "/audio/mi-vereda/transicion_06_espera.webm",
  transicion_07_pausa: "/audio/mi-vereda/transicion_07_pausa.webm",
  transicion_08_repeticion: "/audio/mi-vereda/transicion_08_repeticion.webm",
} as const;

export type GuiaAudioSegmento = "explicacion" | "invitacion" | "confirmacion" | "omitir";

export const GUIA_AUDIO_POR_PASO = {
  bienvenida: {
    explicacion: GUIA_AUDIO_ASSETS.paso_01_bienvenida_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_01_bienvenida_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_01_bienvenida_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_01_bienvenida_omitir,
  },
  "selector-vereda": {
    explicacion: GUIA_AUDIO_ASSETS.paso_02_elegir_vereda_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_02_elegir_vereda_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_02_elegir_vereda_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_02_elegir_vereda_omitir,
  },
  "novedades-activas": {
    explicacion: GUIA_AUDIO_ASSETS.paso_03_novedades_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_03_novedades_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_03_novedades_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_03_novedades_omitir,
  },
  historial: {
    explicacion: GUIA_AUDIO_ASSETS.paso_04_historial_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_04_historial_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_04_historial_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_04_historial_omitir,
  },
  filtros: {
    explicacion: GUIA_AUDIO_ASSETS.paso_05_filtros_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_05_filtros_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_05_filtros_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_05_filtros_omitir,
  },
  solucionado: {
    explicacion: GUIA_AUDIO_ASSETS.paso_06_solucionados_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_06_solucionados_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_06_solucionados_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_06_solucionados_omitir,
  },
  "no-solucionado": {
    explicacion: GUIA_AUDIO_ASSETS.paso_07_no_solucionados_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_07_no_solucionados_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_07_no_solucionados_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_07_no_solucionados_omitir,
  },
  cierre: {
    explicacion: GUIA_AUDIO_ASSETS.paso_08_cierre_explicacion,
    invitacion: GUIA_AUDIO_ASSETS.paso_08_cierre_invitacion,
    confirmacion: GUIA_AUDIO_ASSETS.paso_08_cierre_confirmacion,
    omitir: GUIA_AUDIO_ASSETS.paso_08_cierre_omitir,
  },
} as const;

export const GUIA_AUDIO_TRANSICIONES = {
  preparacion: GUIA_AUDIO_ASSETS.transicion_01_preparacion,
  absorcion: GUIA_AUDIO_ASSETS.transicion_02_absorcion,
  transito: GUIA_AUDIO_ASSETS.transicion_03_transito,
  reaparicion: GUIA_AUDIO_ASSETS.transicion_04_reaparicion,
  senalamiento: GUIA_AUDIO_ASSETS.transicion_05_senalamiento,
  espera: GUIA_AUDIO_ASSETS.transicion_06_espera,
  pausa: GUIA_AUDIO_ASSETS.transicion_07_pausa,
  repeticion: GUIA_AUDIO_ASSETS.transicion_08_repeticion,
} as const;
