/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as EmergenciasRouteImport } from './routes/emergencias'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ViasRouteImport } from './routes/vias'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGestionRouteImport } from './routes/admin/gestion'
import { Route as AdminJacRouteImport } from './routes/admin/jac'
import { Route as AdminJacSuperadminRouteImport } from './routes/admin/jac-superadmin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciasRoute = EmergenciasRouteImport.update({
  id: '/emergencias',
  path: '/emergencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ViasRoute = ViasRouteImport.update({
  id: '/vias',
  path: '/vias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionRoute = AdminGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJacRoute = AdminJacRouteImport.update({
  id: '/jac',
  path: '/jac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJacSuperadminRoute = AdminJacSuperadminRouteImport.update({
  id: '/jac-superadmin',
  path: '/jac-superadmin',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/emergencias': typeof EmergenciasRoute
  '/reportar': typeof ReportarRoute
  '/servicios': typeof ServiciosRoute
  '/vias': typeof ViasRoute
  '/admin/gestion': typeof AdminGestionRoute
  '/admin/jac': typeof AdminJacRoute
  '/admin/jac-superadmin': typeof AdminJacSuperadminRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/emergencias': typeof EmergenciasRoute
  '/reportar': typeof ReportarRoute
  '/servicios': typeof ServiciosRoute
  '/vias': typeof ViasRoute
  '/admin/gestion': typeof AdminGestionRoute
  '/admin/jac': typeof AdminJacRoute
  '/admin/jac-superadmin': typeof AdminJacSuperadminRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/emergencias': typeof EmergenciasRoute
  '/reportar': typeof ReportarRoute
  '/servicios': typeof ServiciosRoute
  '/vias': typeof ViasRoute
  '/admin/gestion': typeof AdminGestionRoute
  '/admin/jac': typeof AdminJacRoute
  '/admin/jac-superadmin': typeof AdminJacSuperadminRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/avisos'
    | '/emergencias'
    | '/reportar'
    | '/servicios'
    | '/vias'
    | '/admin/gestion'
    | '/admin/jac'
    | '/admin/jac-superadmin'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avisos'
    | '/emergencias'
    | '/reportar'
    | '/servicios'
    | '/vias'
    | '/admin/gestion'
    | '/admin/jac'
    | '/admin/jac-superadmin'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/avisos'
    | '/emergencias'
    | '/reportar'
    | '/servicios'
    | '/vias'
    | '/admin/gestion'
    | '/admin/jac'
    | '/admin/jac-superadmin'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvisosRoute: typeof AvisosRoute
  EmergenciasRoute: typeof EmergenciasRoute
  ReportarRoute: typeof ReportarRoute
  ServiciosRoute: typeof ServiciosRoute
  ViasRoute: typeof ViasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencias': {
      id: '/emergencias'
      path: '/emergencias'
      fullPath: '/emergencias'
      preLoaderRoute: typeof EmergenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vias': {
      id: '/vias'
      path: '/vias'
      fullPath: '/vias'
      preLoaderRoute: typeof ViasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestion': {
      id: '/admin/gestion'
      path: '/gestion'
      fullPath: '/admin/gestion'
      preLoaderRoute: typeof AdminGestionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jac': {
      id: '/admin/jac'
      path: '/jac'
      fullPath: '/admin/jac'
      preLoaderRoute: typeof AdminJacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jac-superadmin': {
      id: '/admin/jac-superadmin'
      path: '/jac-superadmin'
      fullPath: '/admin/jac-superadmin'
      preLoaderRoute: typeof AdminJacSuperadminRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGestionRoute: typeof AdminGestionRoute
  AdminJacRoute: typeof AdminJacRoute
  AdminJacSuperadminRoute: typeof AdminJacSuperadminRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGestionRoute: AdminGestionRoute,
  AdminJacRoute: AdminJacRoute,
  AdminJacSuperadminRoute: AdminJacSuperadminRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AvisosRoute: AvisosRoute,
  EmergenciasRoute: EmergenciasRoute,
  ReportarRoute: ReportarRoute,
  ServiciosRoute: ServiciosRoute,
  ViasRoute: ViasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
